// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsAtngUd46k2AxHkN-UyOpfzOzNueCpVo',
    appId: '1:431053953468:web:a7a5e34b4f2576d55173b9',
    messagingSenderId: '431053953468',
    projectId: 'flutter-todo-ab1f8',
    authDomain: 'flutter-todo-ab1f8.firebaseapp.com',
    storageBucket: 'flutter-todo-ab1f8.firebasestorage.app',
    measurementId: 'G-FVFLN12NSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ8KYKat69px9wL1WxKfjBFBWQELzwhME',
    appId: '1:431053953468:android:b3fb61540a5262355173b9',
    messagingSenderId: '431053953468',
    projectId: 'flutter-todo-ab1f8',
    storageBucket: 'flutter-todo-ab1f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjqgjLcI44J0kqb54XyjCl6i5slla3CT4',
    appId: '1:431053953468:ios:50b1b031843d87885173b9',
    messagingSenderId: '431053953468',
    projectId: 'flutter-todo-ab1f8',
    storageBucket: 'flutter-todo-ab1f8.firebasestorage.app',
    iosBundleId: 'com.example.webReserveAcMobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjqgjLcI44J0kqb54XyjCl6i5slla3CT4',
    appId: '1:431053953468:ios:50b1b031843d87885173b9',
    messagingSenderId: '431053953468',
    projectId: 'flutter-todo-ab1f8',
    storageBucket: 'flutter-todo-ab1f8.firebasestorage.app',
    iosBundleId: 'com.example.webReserveAcMobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsAtngUd46k2AxHkN-UyOpfzOzNueCpVo',
    appId: '1:431053953468:web:e5a3c7c36fc825985173b9',
    messagingSenderId: '431053953468',
    projectId: 'flutter-todo-ab1f8',
    authDomain: 'flutter-todo-ab1f8.firebaseapp.com',
    storageBucket: 'flutter-todo-ab1f8.firebasestorage.app',
    measurementId: 'G-PHJF1F3E15',
  );
}
